name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: echo "${{ secrets.ENV }}" > .env
      - name: Build docker Image
        run: docker build --progress=plain -t luongtruong20201/nestjs:v0 .
      - name: "Login to Docker hub"
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: "Push image to docker hub"
        run: docker push luongtruong20201/nestjs:v0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Executing remote ssh command using password"
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
            docker pull luongtruong20201/nestjs:v0
            docker stop nestjs
            docker rm nestjs
            docker run -dp 8000:8000 --name nestjs luongtruong20201/nestjs:v0